name: Create Neon Branch

on:
  workflow_dispatch:
    inputs:
      project_id:
        description: "NexLearn Neon"
        required: true
      branch:
        description: "Dev Branch"
        required: true

jobs:
  create-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Neon Branch
        uses: neon-tech/create-neon-branch@v1
        with:
          project_id: ${{ github.event.inputs.project_id }}
          branch: ${{ github.event.inputs.branch }}
          api_key: ${{ secrets.NEON_API_KEY }}
