name: Delete Neon Branch with GitHub Actions Demo

run-name: Delete a Neon Branch 🚀

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  delete-neon-branch:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Delete Neon Branch
        uses: neondatabase/delete-branch-action@v3
        with:
          project_id: lingering-hill-03805833
          branch: ${{ github.ref_name }}
          api_key: ${{ secrets.NEON_API_KEY }}
