name: Reset Neon Branch with GitHub Actions Demo

on:
  workflow_dispatch:

jobs:
  Reset-Neon-Branch:
    runs-on: ubuntu-latest
    steps:
      - name: Reset Neon Branch
        uses: neondatabase/reset-branch-action@v1
        with:
          project_id: rapid-haze-373089
          parent: true
          branch: child_branch
          api_key: ${{ secrets.NEON_API_KEY }}
        id: reset-branch

      - name: Echo Branch ID
        run: echo branch_id ${{ steps.reset-branch.outputs.branch_id }}
